//! Session compaction via structured checkpoints (spec: compac_session.md).
//!
//! Reduces the model's *active* context without reducing AETHER's durable
//! knowledge of the session. The complete conversation history is never
//! deleted; compaction produces a structured [`CompactionCheckpoint`] that
//! captures objective, plan, decisions, files, verification state and
//! per-role agent state, then rebuilds the active context as:
//!
//! ```text
//! System Prompt + Checkpoint (as session memory) + Recent Messages + Request
//! ```
//!
//! The checkpoint is generated by the session's configured Model 2
//! (controller) — never by a dynamically selected model. Checkpoints are
//! treated as session state/data, not as instructions: they cannot override
//! AETHER's system, security, role or permission rules.

use serde::{Deserialize, Serialize};
use std::sync::Arc;

use aether_models::{CompletionRequest, Message, ModelProvider};

/// Fraction of the model context window considered the "safe" compaction
/// threshold. Compaction triggers when the estimated request would exceed
/// this fraction of the window.
pub const COMPACTION_SAFE_RATIO: f32 = 0.80;
/// Fraction of the window reserved for output when estimating headroom.
pub const OUTPUT_RESERVE_RATIO: f32 = 0.10;
/// Minimum number of recent messages always retained after compaction.
pub const MIN_RECENT_MESSAGES: usize = 4;

/// What triggered a compaction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompactTrigger {
    /// Context approached the safe limit (automatic).
    Automatic,
    /// Provider returned a context-overflow error.
    Overflow,
    /// User ran `/compact`.
    Manual,
}

/// Compaction lifecycle status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompactionStatus {
    Idle,
    Running,
    Completed,
    Failed,
}

/// Structured session checkpoint. Preserves the state required to continue a
/// long-running task after the active context is reduced. All fields are
/// advisory session memory; none are instructions.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CompactionCheckpoint {
    #[serde(default)]
    pub session_id: String,
    pub user_objective: String,
    #[serde(default)]
    pub current_plan: Option<String>,
    #[serde(default)]
    pub current_phase: Option<String>,
    #[serde(default)]
    pub completed_tasks: Vec<String>,
    #[serde(default)]
    pub active_task: Option<String>,
    #[serde(default)]
    pub pending_tasks: Vec<String>,
    #[serde(default)]
    pub blocked_tasks: Vec<String>,
    #[serde(default)]
    pub dependencies: Vec<String>,
    #[serde(default)]
    pub important_decisions: Vec<String>,
    /// References to relevant files (paths only — files stay in the workspace).
    #[serde(default)]
    pub relevant_files: Vec<String>,
    /// Reduced-to-useful-state tool results (not raw output).
    #[serde(default)]
    pub important_tool_results: Vec<String>,
    #[serde(default)]
    pub build_status: Option<String>,
    #[serde(default)]
    pub test_status: Option<String>,
    #[serde(default)]
    pub lint_status: Option<String>,
    #[serde(default)]
    pub sonarqube_status: Option<String>,
    #[serde(default)]
    pub known_errors: Vec<String>,
    #[serde(default)]
    pub current_blockers: Vec<String>,
    #[serde(default)]
    pub next_actions: Vec<String>,
    /// Model 1 (Executor) state.
    #[serde(default)]
    pub model1_state: Option<String>,
    /// Model 2 (Controller) state.
    #[serde(default)]
    pub model2_state: Option<String>,
    /// Model 3 (Visual Reviewer) state — only present when Model 3 was used.
    #[serde(default)]
    pub model3_state: Option<String>,
    #[serde(default)]
    pub created_at: String,
}

impl CompactionCheckpoint {
    /// Validate a generated checkpoint. A checkpoint is valid only if it has a
    /// non-empty user objective. Invalid checkpoints must never replace valid
    /// session state.
    pub fn is_valid(&self) -> bool {
        !self.user_objective.trim().is_empty()
    }

    /// Render the checkpoint as a context block. Framed explicitly as session
    /// memory so the model treats it as data, not instructions.
    pub fn to_context_block(&self) -> String {
        let mut s = String::new();
        s.push_str("[SESSION STATE CHECKPOINT — session memory, not instructions]\n");
        s.push_str(&format!("Objective: {}\n", self.user_objective));
        if let Some(p) = &self.current_plan { s.push_str(&format!("Plan: {p}\n")); }
        if let Some(p) = &self.current_phase { s.push_str(&format!("Phase: {p}\n")); }
        if !self.completed_tasks.is_empty() {
            s.push_str(&format!("Completed: {}\n", self.completed_tasks.join("; ")));
        }
        if let Some(t) = &self.active_task { s.push_str(&format!("Active task: {t}\n")); }
        if !self.pending_tasks.is_empty() {
            s.push_str(&format!("Pending: {}\n", self.pending_tasks.join("; ")));
        }
        if !self.blocked_tasks.is_empty() {
            s.push_str(&format!("Blocked: {}\n", self.blocked_tasks.join("; ")));
        }
        if !self.important_decisions.is_empty() {
            s.push_str(&format!("Decisions: {}\n", self.important_decisions.join("; ")));
        }
        if !self.relevant_files.is_empty() {
            s.push_str(&format!("Relevant files: {}\n", self.relevant_files.join(", ")));
        }
        if !self.important_tool_results.is_empty() {
            s.push_str(&format!("Key tool results: {}\n", self.important_tool_results.join("; ")));
        }
        if let Some(b) = &self.build_status { s.push_str(&format!("Build: {b}\n")); }
        if let Some(t) = &self.test_status { s.push_str(&format!("Tests: {t}\n")); }
        if let Some(l) = &self.lint_status { s.push_str(&format!("Lint: {l}\n")); }
        if let Some(q) = &self.sonarqube_status { s.push_str(&format!("SonarQube: {q}\n")); }
        if !self.known_errors.is_empty() {
            s.push_str(&format!("Known errors: {}\n", self.known_errors.join("; ")));
        }
        if !self.current_blockers.is_empty() {
            s.push_str(&format!("Blockers: {}\n", self.current_blockers.join("; ")));
        }
        if !self.next_actions.is_empty() {
            s.push_str(&format!("Next actions: {}\n", self.next_actions.join("; ")));
        }
        if let Some(m) = &self.model1_state { s.push_str(&format!("Executor state: {m}\n")); }
        if let Some(m) = &self.model2_state { s.push_str(&format!("Controller state: {m}\n")); }
        if let Some(m) = &self.model3_state { s.push_str(&format!("Reviewer state: {m}\n")); }
        s.push_str("[END CHECKPOINT]");
        s
    }
}

/// Persistence for checkpoints. Implemented over the session store so each
/// session's checkpoint is isolated. Synchronous because the backing store
/// (rusqlite) is synchronous.
pub trait CheckpointStore: Send + Sync {
    fn save_checkpoint(&self, session_id: &str, checkpoint: &CompactionCheckpoint) -> Result<(), String>;
    fn load_checkpoint(&self, session_id: &str) -> Result<Option<CompactionCheckpoint>, String>;
}

/// In-memory checkpoint store (tests + fallback).
#[derive(Default)]
pub struct MemoryCheckpointStore {
    map: parking_lot::Mutex<std::collections::HashMap<String, CompactionCheckpoint>>,
}

impl CheckpointStore for MemoryCheckpointStore {
    fn save_checkpoint(&self, session_id: &str, checkpoint: &CompactionCheckpoint) -> Result<(), String> {
        self.map.lock().insert(session_id.to_string(), checkpoint.clone());
        Ok(())
    }
    fn load_checkpoint(&self, session_id: &str) -> Result<Option<CompactionCheckpoint>, String> {
        Ok(self.map.lock().get(session_id).cloned())
    }
}

/// Rough token estimator (chars/4). Consistent with the rest of the crate.
pub fn estimate_message_tokens(msgs: &[Message]) -> u32 {
    msgs.iter()
        .map(|m| (m.content.chars().count() as u32) / 4 + 16)
        .sum()
}

/// Estimate the total tokens a request will consume, accounting for system
/// prompt, tool schemas and conversation history.
pub fn estimate_request_tokens(
    system_prompt: &str,
    tool_schemas: &[serde_json::Value],
    messages: &[Message],
) -> u32 {
    let sys = (system_prompt.chars().count() as u32) / 4 + 16;
    let tools: u32 = tool_schemas
        .iter()
        .map(|t| (t.to_string().chars().count() as u32) / 4)
        .sum();
    sys + tools + estimate_message_tokens(messages)
}

/// Decide whether compaction is needed before sending a request.
pub fn should_compact(estimated_tokens: u32, context_window: u32) -> bool {
    if context_window == 0 {
        return false;
    }
    let limit = (context_window as f32 * (COMPACTION_SAFE_RATIO - OUTPUT_RESERVE_RATIO)) as u32;
    estimated_tokens >= limit
}

/// The session compactor. Uses the session's configured Model 2 (controller)
/// to generate structured checkpoints. No routing, no model switching.
pub struct SessionCompactor {
    controller: Arc<dyn ModelProvider>,
    controller_model: String,
    context_window: u32,
    store: Arc<dyn CheckpointStore>,
    status: parking_lot::Mutex<CompactionStatus>,
}

impl std::fmt::Debug for SessionCompactor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SessionCompactor")
            .field("controller_model", &self.controller_model)
            .field("context_window", &self.context_window)
            .finish()
    }
}

impl SessionCompactor {
    pub fn new(
        controller: Arc<dyn ModelProvider>,
        controller_model: String,
        context_window: u32,
        store: Arc<dyn CheckpointStore>,
    ) -> Self {
        Self {
            controller,
            controller_model,
            context_window,
            store,
            status: parking_lot::Mutex::new(CompactionStatus::Idle),
        }
    }

    pub fn status(&self) -> CompactionStatus { *self.status.lock() }
    pub fn context_window(&self) -> u32 { self.context_window }

    /// Load the most recent persisted checkpoint for a session (if any).
    pub fn load_checkpoint(&self, session_id: &str) -> Option<CompactionCheckpoint> {
        self.store.load_checkpoint(session_id).ok().flatten()
    }

    /// Generate a structured checkpoint from the conversation using Model 2.
    /// Returns `None` if generation or validation fails (previous state is
    /// preserved by the caller).
    async fn generate_checkpoint(
        &self,
        session_id: &str,
        messages: &[Message],
    ) -> Option<CompactionCheckpoint> {
        let transcript = render_transcript(messages);
        let prompt = format!(
            "{}\n\n---\nSESSION TRANSCRIPT:\n{}",
            CHECKPOINT_SYSTEM_PROMPT, transcript
        );
        let req = CompletionRequest {
            model: self.controller_model.clone(),
            messages: vec![Message {
                role: "user".into(),
                content: prompt,
                ..Default::default()
            }],
            temperature: Some(0.0),
            ..Default::default()
        };
        let resp = match self.controller.complete(req).await {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("checkpoint generation failed: {e}");
                return None;
            }
        };
        let raw = resp.content.unwrap_or_default();
        let json = extract_json(&raw)?;
        let mut checkpoint: CompactionCheckpoint = match serde_json::from_str(&json) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!("checkpoint parse failed: {e}");
                return None;
            }
        };
        checkpoint.session_id = session_id.to_string();
        checkpoint.created_at = chrono::Utc::now().to_rfc3339();
        if !checkpoint.is_valid() {
            tracing::warn!("checkpoint invalid (empty objective); keeping previous state");
            return None;
        }
        Some(checkpoint)
    }

    /// Run a full compaction cycle. Atomic: the active context is only rebuilt
    /// after the checkpoint is generated, validated and persisted. On any
    /// failure the previous state is retained and `Err` is returned.
    ///
    /// Returns the rebuilt message list (system + checkpoint + recent tail).
    pub async fn compact(
        &self,
        session_id: &str,
        system_prompt: &str,
        messages: &[Message],
        trigger: CompactTrigger,
    ) -> Result<Vec<Message>, CompactionError> {
        *self.status.lock() = CompactionStatus::Running;

        let checkpoint = self
            .generate_checkpoint(session_id, messages)
            .await
            .ok_or(CompactionError::GenerationFailed)?;

        // Persist before rebuilding (atomic: never half-compacted).
        self.store
            .save_checkpoint(session_id, &checkpoint)
            .map_err(|e| CompactionError::PersistFailed(e))?;

        let rebuilt = rebuild_context(
            system_prompt,
            &checkpoint,
            messages,
            self.context_window,
        );

        *self.status.lock() = CompactionStatus::Completed;
        tracing::info!(
            session = session_id,
            trigger = ?trigger,
            "context compacted: {} -> {} tokens",
            estimate_message_tokens(messages),
            estimate_message_tokens(&rebuilt),
        );
        Ok(rebuilt)
    }
}

/// Errors from a compaction cycle.
#[derive(Debug, thiserror::Error)]
pub enum CompactionError {
    #[error("checkpoint generation failed or produced an invalid checkpoint")]
    GenerationFailed,
    #[error("checkpoint persistence failed: {0}")]
    PersistFailed(String),
}

/// Rebuild the active context: system prompt + checkpoint (as memory) + as
/// many recent messages as fit the remaining budget. The recent-tail size is
/// determined dynamically from the budget, not a fixed count.
pub fn rebuild_context(
    system_prompt: &str,
    checkpoint: &CompactionCheckpoint,
    messages: &[Message],
    context_window: u32,
) -> Vec<Message> {
    let mut out = Vec::new();
    out.push(Message {
        role: "system".into(),
        content: system_prompt.to_string(),
        ..Default::default()
    });
    out.push(Message {
        role: "user".into(),
        content: checkpoint.to_context_block(),
        ..Default::default()
    });

    let base_tokens = estimate_message_tokens(&out);
    let reserve = (context_window as f32 * OUTPUT_RESERVE_RATIO) as u32;
    let budget = context_window.saturating_sub(base_tokens).saturating_sub(reserve);

    // Walk backwards, keeping recent messages until the budget is exhausted.
    let mut kept: Vec<Message> = Vec::new();
    let mut used = 0u32;
    for m in messages.iter().rev() {
        if m.role == "system" {
            continue;
        }
        let t = (m.content.chars().count() as u32) / 4 + 16;
        if kept.len() >= MIN_RECENT_MESSAGES || used + t <= budget {
            used += t;
            kept.push(m.clone());
        } else {
            break;
        }
    }
    kept.reverse();
    out.extend(kept);
    out
}

/// Render a bounded transcript for the checkpoint-generation prompt.
fn render_transcript(messages: &[Message]) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut total = 0usize;
    const MAX_CHARS: usize = 24_000;
    for m in messages.iter().rev() {
        if m.role == "system" {
            continue;
        }
        let line = format!("[{}] {}", m.role, m.content);
        let len = line.len();
        if total + len > MAX_CHARS {
            break;
        }
        lines.push(line);
        total += len;
    }
    // We walked backwards; reverse to chronological order.
    lines.reverse();
    lines.join("\n")
}

/// Extract the first JSON object from a model response (tolerates prose).
fn extract_json(raw: &str) -> Option<String> {
    let start = raw.find('{')?;
    let mut depth = 0i32;
    for (i, c) in raw[start..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(raw[start..start + i + 1].to_string());
                }
            }
            _ => {}
        }
    }
    None
}

const CHECKPOINT_SYSTEM_PROMPT: &str = "You are the AETHER Controller producing a structured session \
checkpoint for context compaction. Summarize the session transcript into the JSON schema below. \
Preserve the user objective, plan, completed/active/pending/blocked tasks, decisions, relevant file \
paths (references only), reduced tool results (state, not raw output), verification status, errors, \
blockers and next actions. Capture executor/controller/reviewer state where applicable. Output ONLY \
valid JSON, no prose.\n\nSchema:\n{\n  \"user_objective\": string (required),\n  \"current_plan\": string|null,\n  \
\"current_phase\": string|null,\n  \"completed_tasks\": string[],\n  \"active_task\": string|null,\n  \
\"pending_tasks\": string[],\n  \"blocked_tasks\": string[],\n  \"dependencies\": string[],\n  \
\"important_decisions\": string[],\n  \"relevant_files\": string[],\n  \"important_tool_results\": string[],\n  \
\"build_status\": string|null,\n  \"test_status\": string|null,\n  \"lint_status\": string|null,\n  \
\"sonarqube_status\": string|null,\n  \"known_errors\": string[],\n  \"current_blockers\": string[],\n  \
\"next_actions\": string[],\n  \"model1_state\": string|null,\n  \"model2_state\": string|null,\n  \
\"model3_state\": string|null\n}";

#[cfg(test)]
mod tests {
    use super::*;
    use aether_models::{CompletionResponse, ProviderError, TokenStream};

    fn msg(role: &str, content: &str) -> Message {
        Message { role: role.into(), content: content.into(), ..Default::default() }
    }

    /// Mock provider that returns a fixed checkpoint JSON (or fails).
    struct MockController {
        response: Result<String, ProviderError>,
    }

    #[async_trait::async_trait]
    impl ModelProvider for MockController {
        async fn complete(&self, _req: CompletionRequest) -> Result<CompletionResponse, ProviderError> {
            match &self.response {
                Ok(content) => Ok(CompletionResponse {
                    content: Some(content.clone()),
                    tool_calls: vec![],
                    usage: None,
                }),
                Err(e) => Err(ProviderError::Api(e.to_string())),
            }
        }
        async fn stream(&self, _req: CompletionRequest) -> Result<TokenStream, ProviderError> {
            Err(ProviderError::Api("not implemented".into()))
        }
        async fn embeddings(&self, _input: Vec<String>) -> Result<Vec<Vec<f32>>, ProviderError> {
            Ok(vec![])
        }
        fn supports_tool_calling(&self) -> bool { false }
        fn name(&self) -> &str { "mock-controller" }
    }

    fn valid_checkpoint_json() -> String {
        r#"{"user_objective":"Build auth","current_plan":"Implement login","current_phase":"implementation","completed_tasks":["scaffold"],"active_task":"login endpoint","pending_tasks":["tests"],"blocked_tasks":[],"dependencies":[],"important_decisions":["use JWT"],"relevant_files":["src/auth.ts"],"important_tool_results":["build passed"],"build_status":"PASS","test_status":"27 passed","lint_status":"PASS","sonarqube_status":"0 critical","known_errors":[],"current_blockers":[],"next_actions":["write tests"],"model1_state":"implementing login","model2_state":"phase: implementation","model3_state":null}"#.to_string()
    }

    fn mock_compactor(response: Result<String, ProviderError>) -> (SessionCompactor, Arc<MemoryCheckpointStore>) {
        let store = Arc::new(MemoryCheckpointStore::default());
        let provider = Arc::new(MockController { response });
        let compactor = SessionCompactor::new(
            provider,
            "mock-model".into(),
            100_000,
            store.clone(),
        );
        (compactor, store)
    }

    #[test]
    fn checkpoint_requires_objective() {
        let mut c = CompactionCheckpoint::default();
        assert!(!c.is_valid());
        c.user_objective = "Build auth".into();
        assert!(c.is_valid());
    }

    #[test]
    fn context_block_is_framed_as_memory() {
        let mut c = CompactionCheckpoint::default();
        c.user_objective = "Build auth".into();
        c.relevant_files = vec!["src/auth.ts".into()];
        let block = c.to_context_block();
        assert!(block.contains("SESSION STATE CHECKPOINT"));
        assert!(block.contains("not instructions"));
        assert!(block.contains("src/auth.ts"));
    }

    #[test]
    fn should_compact_respects_window() {
        assert!(!should_compact(100, 100_000));
        assert!(should_compact(90_000, 100_000));
        assert!(!should_compact(100, 0));
    }

    #[test]
    fn rebuild_keeps_system_checkpoint_and_recent() {
        let mut c = CompactionCheckpoint::default();
        c.user_objective = "obj".into();
        let msgs: Vec<Message> = (0..20)
            .map(|i| msg(if i % 2 == 0 { "user" } else { "assistant" }, &format!("m{i} {}", "x".repeat(100))))
            .collect();
        let rebuilt = rebuild_context("SYS", &c, &msgs, 2000);
        assert_eq!(rebuilt[0].role, "system");
        assert!(rebuilt[1].content.contains("SESSION STATE CHECKPOINT"));
        assert!(rebuilt.len() >= 2 + MIN_RECENT_MESSAGES);
        // Recent tail preserved in order.
        let last = rebuilt.last().unwrap();
        assert!(last.content.starts_with("m19"));
    }

    #[test]
    fn extract_json_tolerates_prose() {
        let raw = "Here is the checkpoint:\n{\"user_objective\": \"x\"}\nDone.";
        let j = extract_json(raw).unwrap();
        assert_eq!(j, "{\"user_objective\": \"x\"}");
    }

    #[test]
    fn memory_store_isolates_sessions() {
        let store = MemoryCheckpointStore::default();
        let mut a = CompactionCheckpoint::default();
        a.user_objective = "A".into();
        store.save_checkpoint("sess-a", &a).unwrap();
        assert!(store.load_checkpoint("sess-a").unwrap().is_some());
        assert!(store.load_checkpoint("sess-b").unwrap().is_none());
    }

    // ---- Async compaction tests (spec §21) ----

    #[tokio::test]
    async fn automatic_compaction_generates_and_persists_checkpoint() {
        let (compactor, store) = mock_compactor(Ok(valid_checkpoint_json()));
        let msgs: Vec<Message> = (0..30)
            .map(|i| msg("user", &format!("message {i} {}", "y".repeat(200))))
            .collect();
        let rebuilt = compactor
            .compact("sess-1", "SYS", &msgs, CompactTrigger::Automatic)
            .await
            .unwrap();
        // Checkpoint persisted.
        let cp = store.load_checkpoint("sess-1").unwrap().unwrap();
        assert_eq!(cp.user_objective, "Build auth");
        assert_eq!(cp.relevant_files, vec!["src/auth.ts"]);
        assert_eq!(cp.build_status.as_deref(), Some("PASS"));
        // Rebuilt context is smaller and starts with system + checkpoint.
        assert_eq!(rebuilt[0].role, "system");
        assert!(rebuilt[1].content.contains("SESSION STATE CHECKPOINT"));
        assert_eq!(compactor.status(), CompactionStatus::Completed);
    }

    #[tokio::test]
    async fn manual_compaction_uses_manual_trigger() {
        let (compactor, store) = mock_compactor(Ok(valid_checkpoint_json()));
        let msgs = vec![msg("user", "do the thing")];
        let _ = compactor
            .compact("sess-m", "SYS", &msgs, CompactTrigger::Manual)
            .await
            .unwrap();
        assert!(store.load_checkpoint("sess-m").unwrap().is_some());
    }

    #[tokio::test]
    async fn invalid_checkpoint_keeps_previous_state() {
        // Model returns malformed JSON → compaction fails, nothing persisted.
        let (compactor, store) = mock_compactor(Ok("not json at all".into()));
        let msgs = vec![msg("user", "task")];
        let res = compactor.compact("sess-x", "SYS", &msgs, CompactTrigger::Automatic).await;
        assert!(res.is_err());
        assert!(store.load_checkpoint("sess-x").unwrap().is_none());
        assert_eq!(compactor.status(), CompactionStatus::Running); // not Completed
    }

    #[tokio::test]
    async fn empty_objective_checkpoint_is_rejected() {
        let (compactor, store) = mock_compactor(Ok(r#"{"user_objective":""}"#.into()));
        let msgs = vec![msg("user", "task")];
        let res = compactor.compact("sess-y", "SYS", &msgs, CompactTrigger::Automatic).await;
        assert!(res.is_err());
        assert!(store.load_checkpoint("sess-y").unwrap().is_none());
    }

    #[tokio::test]
    async fn provider_failure_keeps_previous_state() {
        let (compactor, store) = mock_compactor(Err(ProviderError::Api("boom".into())));
        let msgs = vec![msg("user", "task")];
        let res = compactor.compact("sess-z", "SYS", &msgs, CompactTrigger::Overflow).await;
        assert!(res.is_err());
        assert!(store.load_checkpoint("sess-z").unwrap().is_none());
    }

    #[tokio::test]
    async fn session_isolation_across_compactions() {
        let (compactor, store) = mock_compactor(Ok(valid_checkpoint_json()));
        let msgs = vec![msg("user", "task")];
        compactor.compact("sess-a", "SYS", &msgs, CompactTrigger::Manual).await.unwrap();
        // Session B has no checkpoint.
        assert!(store.load_checkpoint("sess-b").unwrap().is_none());
        assert!(store.load_checkpoint("sess-a").unwrap().is_some());
    }
}
